/** Equipment inventory: one independently editable row per imported source line. */
export const inventoryStatuses=['DISPONIBLE','POR SALIR','PENDIENTE DE PRUEBA','INHABILITADO','DAÑADO','ENTREGADO','POR VALIDAR'];
export const inventorySerialKey=v=>String(v??'').toUpperCase().replace(/\s+/g,'').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=v=>String(v??'').replace(/\u00a0/g,' ').trim();
const cssStatus=s=>'inv-state-'+String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-');
export function inventoryTickets(row,tickets){
 const keys=new Set([inventorySerialKey(row.serial_number),inventorySerialKey(row.source_snapshot?.serial_number)]);
 keys.delete('');
 return tickets.filter(t=>keys.has(inventorySerialKey(t.serial)));
}
export function renderInventoryEquipment({inventory=[],tickets=[],query='',status='',archiveMode='active',page=1,pageSize=20}={}){
 const active=inventory.filter(r=>!r.archived),counts={};
 for(const r of active){counts[r.status]=(counts[r.status]||0)+1;}
 const serialCounts={};for(const r of active){const key=inventorySerialKey(r.serial_number);serialCounts[key]=(serialCounts[key]||0)+1;}
 const q=normalize(query).toLocaleLowerCase('es');
 const rows=inventory.filter(r=>(archiveMode==='archived'?r.archived:!r.archived)&&(!status||r.status===status)&&(!q||[r.serial_number,r.model,r.extraction_ref,r.product_line,r.equipment_type,r.client_name,r.status].some(v=>String(v||'').toLocaleLowerCase('es').includes(q))));
 const pages=Math.max(1,Math.ceil(rows.length/pageSize)),current=Math.max(1,Math.min(page,pages)),start=(current-1)*pageSize,visible=rows.slice(start,start+pageSize);
 const metric=(value,label,tone='')=>'<div class="inv-metric '+tone+'"><strong>'+value+'</strong><small>'+label+'</small></div>';
 const metrics='<div class="inv-metrics">'+metric(active.length,'Registros activos')+metric(counts.DISPONIBLE||0,'Disponibles','good')+metric(counts['POR SALIR']||0,'Por salir','warn')+metric(counts['PENDIENTE DE PRUEBA']||0,'Pendientes prueba','warn')+metric(counts.INHABILITADO||0,'Inhabilitados','bad')+metric(counts.ENTREGADO||0,'Entregados')+'</div>';
 const filters='<div class="inv-controls"><label>Buscar equipo<input type="search" id="inventorySearch" value="'+esc(query)+'" placeholder="Serie, modelo o extracción" autocomplete="off"></label><label>Estado<select id="inventoryStatus"><option value="">Todos</option>'+inventoryStatuses.map(s=>'<option '+(status===s?'selected':'')+'>'+esc(s)+'</option>').join('')+'</select></label><label>Mostrar<select id="inventoryArchiveMode"><option value="active" '+(archiveMode==='active'?'selected':'')+'>Activos</option><option value="archived" '+(archiveMode==='archived'?'selected':'')+'>Archivados</option></select></label></div>';
 const cards='<div class="card-grid inv-cards">'+visible.map(r=>{
  const duplicates=serialCounts[inventorySerialKey(r.serial_number)]||0,related=inventoryTickets(r,tickets);
  return '<button class="entity-card inv-card" data-action="inventory-detail" data-id="'+esc(r.id)+'"><span class="entity-card-top"><span class="entity-icon">⚙</span><span class="inv-state '+cssStatus(r.status)+'">'+esc(r.archived?'ARCHIVADO':r.status)+'</span></span><h2>'+esc(r.model||'Sin modelo')+'</h2><p>Serie: '+esc(r.serial_number)+'</p><p>Extracción: '+esc(r.extraction_ref||'Sin dato')+'</p><span class="entity-card-foot"><span>'+related.length+' tickets</span>'+(duplicates>1?'<span class="inv-repeated">Serie repetida ×'+duplicates+'</span>':'<span>Editar ↗</span>')+'</span></button>';
 }).join('')+'</div>';
 const duplicates=Object.values(serialCounts).filter(x=>x>1).length;
 return {page:current,html:'<section class="inv-view">'+metrics+'<div class="view-summary"><span><b>'+Object.keys(serialCounts).length+'</b> series distintas · '+active.length+' registros activos</span><span>'+duplicates+' serie(s) repetida(s)</span></div>'+filters+(visible.length?cards:'<p class="definition-note">Sin registros coincidentes.</p>')+'<div class="inv-page"><span>'+rows.length+' registros · página '+current+'/'+pages+'</span><div><button class="button secondary" data-action="inventory-page" data-delta="-1" '+(current<=1?'disabled':'')+'>‹ Anterior</button><button class="button secondary" data-action="inventory-page" data-delta="1" '+(current>=pages?'disabled':'')+'>Siguiente ›</button></div></div><p class="definition-note">Cada renglón de almacén se conserva individualmente, incluso cuando la serie se repite. Corregir o archivar esta ficha no altera tickets anteriores.</p></section>'};
}
const field=(id,label,value,opts='')=>'<label class="inv-field">'+esc(label)+'<input id="inv'+id+'" value="'+esc(value??'')+'" '+opts+'></label>';
export function renderInventoryDetails(row,inventory=[],tickets=[]){
 const originals=row.source_snapshot||{};
 const duplicates=inventory.filter(r=>r.id!==row.id&&!r.archived&&inventorySerialKey(r.serial_number)===inventorySerialKey(row.serial_number));
 const linked=inventoryTickets(row,tickets);
 const statuses=inventoryStatuses.map(s=>'<option value="'+esc(s)+'" '+(row.status===s?'selected':'')+'>'+esc(s)+'</option>').join('');
 return '<div class="inv-detail"><section class="detail-section"><h3>'+esc(row.model)+'</h3><p><b>Serie:</b> '+esc(row.serial_number)+'</p><span class="inv-state '+cssStatus(row.status)+'">'+esc(row.archived?'ARCHIVADO':row.status)+'</span>'+(duplicates.length?'<p class="inv-alert">⚠ Esta serie aparece '+(duplicates.length+1)+' veces en el inventario. Ambas fichas se conservaron.</p>':'')+'<p class="definition-note">Origen: inventario de almacén · renglón '+esc(row.source_row)+'. Se conservó una copia de los datos originales.</p></section><section class="detail-section"><h3>Editar datos del equipo</h3><div class="inv-fields">'+field('Serial','Número de serie',row.serial_number,'required maxlength="100"')+field('Model','Modelo',row.model,'required maxlength="180"')+field('Extraction','Extracción',row.extraction_ref,'maxlength="100"')+field('Line','Línea',row.product_line,'maxlength="120"')+field('Type','Tipo de equipo',row.equipment_type,'maxlength="140"')+field('Client','Cliente / destino (opcional)',row.client_name,'maxlength="200"')+'<label class="inv-field">Estado<select id="invStatus">'+statuses+'</select></label>'+field('Quantity','Cantidad',row.quantity,'type="number" min="1" max="10000" required')+'<label class="inv-field inv-wide">Observaciones<textarea id="invNotes" maxlength="2000" rows="3">'+esc(row.notes||'')+'</textarea></label></div><div class="inv-buttons"><button type="button" class="button primary" data-action="inventory-save" data-id="'+esc(row.id)+'">Guardar cambios</button><button type="button" class="button secondary" data-action="inventory-archive" data-id="'+esc(row.id)+'">'+(row.archived?'Restaurar registro':'Archivar registro')+'</button></div><p class="definition-note">Archivar retira la ficha del inventario activo, sin destruir su historial; se puede restaurar.</p></section><section class="detail-section"><h3>Tickets vinculados por serie ('+linked.length+')</h3>'+(linked.length?linked.map(t=>'<button class="task-row" data-action="ticket" data-id="'+esc(t.id)+'"><span><b>#'+esc(t.folio)+'</b> · '+esc(t.title||'Sin descripción')+'<small>'+esc(t.client||'Sin cliente')+' · '+esc(t.status)+'</small></span><span>Ver ticket ↗</span></button>').join(''):'<p class="definition-note">Aún no se localizaron tickets asociados a esta serie.</p>')+'</section><details class="detail-section"><summary>Datos originales sin modificar</summary><p>Serie: '+esc(originals.serial_number||row.serial_number)+'</p><p>Modelo: '+esc(originals.model||row.model)+'</p><p>Extracción: '+esc(originals.extraction_ref||'Sin dato')+'</p><p>Estado: '+esc(originals.status||row.status)+'</p></details></div>';
}
